version: "3"

dotenv:
  - .task.env

tasks:
  lint:
    desc: Lint the code
    cmds:
      - cmd: black ./backend
      #- cmd: isort ./backend
      #- cmd: pylint ./backend
      #- cmd: mypy ./backend
      #- cmd: pyright ./backend
