version: "3"

includes:
  backend: backend/taskfile.yml
  frontend: frontend/taskfile.yml

tasks:
  lint:
    desc: Lint the code
    cmds:
      - task: backend:lint

  run_back:
    desc: Run the backend server
    cmds:
      - task: backend:run_server

  run_front:
    desc: Run the frontend server
    cmds:
      - task: frontend:run_server
